### ISSUE TITLE
Running goss requires `boost`

### ISSUE THREAD

**Issue by finsberg** [ComputationalPhysiology/goss#13]
When running any of the demo in a fresh environment without boost, gives the following error

```
python oscilator_v1.py 
Loaded ODE model 'oscilator' with:
     Num full states: 2
      Num parameters: 0
Traceback (most recent call last):
  File "oscilator_v1.py", line 36, in <module>
    oscilator = goss.ODE(load_ode("oscilator.ode"))
  File "/venv/lib/python3.7/site-packages/goss/ode.py", line 22, in __init__
    self._cpp_object = jit(args[0], **kwargs)
  File "/venv/lib/python3.7/site-packages/goss/compilemodule.py", line 113, in jit
    code_params=code_params,
  File "/venv/lib/python3.7/site-packages/goss/compilemodule.py", line 67, in cppyy_jit
    cppyy.cppdef(cpp_code)
  File "/venv/lib/python3.7/site-packages/cppyy/__init__.py", line 196, in cppdef
    raise SyntaxError('Failed to parse the given C++ code%s' % err.err)
SyntaxError: Failed to parse the given C++ code
In file included from input_line_21:18:
In file included from /venv/lib/python3.7/site-packages/goss/include/goss/Timer.h:30:
In file included from /venv/lib/python3.7/site-packages/goss/include/goss/LogManager.h:26:
/venv/lib/python3.7/site-packages/goss/include/goss/Logger.h:31:10: fatal error: 'boost/scoped_ptr.hpp' file not found
#include <boost/scoped_ptr.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~
````

**Comment by finsberg** [comment]
Fixed in https://github.com/ComputationalPhysiology/goss/pull/14 

We cannot distribute wheels since we have a c++ dependency needed at runtime. This will be fixed if we provide a conda package.
